/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TokenExpiresImport } from './routes/token-expires'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as DashboardSetttingImport } from './routes/dashboard/settting'
import { Route as DashboardLayoutImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexImport } from './routes/dashboard/_layout/index'
import { Route as LayoutThanksIndexImport } from './routes/_layout/thanks/index'
import { Route as LayoutShopIndexImport } from './routes/_layout/shop/index'
import { Route as LayoutSearchListIndexImport } from './routes/_layout/searchList/index'
import { Route as LayoutProfileIndexImport } from './routes/_layout/profile/index'
import { Route as LayoutPaymentOnlineIndexImport } from './routes/_layout/payment-online/index'
import { Route as LayoutOrderuserIndexImport } from './routes/_layout/orderuser/index'
import { Route as LayoutCheckoutNewIndexImport } from './routes/_layout/checkoutNew/index'
import { Route as LayoutCheckoutIndexImport } from './routes/_layout/checkout/index'
import { Route as LayoutChangepasswordIndexImport } from './routes/_layout/change_password/index'
import { Route as LayoutCartIndexImport } from './routes/_layout/cart/index'
import { Route as LayoutBlogIndexImport } from './routes/_layout/blog/index'
import { Route as LayoutAddressIndexImport } from './routes/_layout/address/index'
import { Route as LayoutAboutIndexImport } from './routes/_layout/about/index'
import { Route as LayoutDetailblogSlugImport } from './routes/_layout/detailblog/$slug'
import { Route as LayoutCategoriesSlugImport } from './routes/_layout/categories/$slug'
import { Route as LayoutBlogTextImport } from './routes/_layout/blog/text'
import { Route as LayoutSlugQuickviewProductImport } from './routes/_layout/$slug.quickviewProduct'
import { Route as LayoutSlugDetailproductImport } from './routes/_layout/$slug.detailproduct'
import { Route as DashboardLayoutUsersIndexImport } from './routes/dashboard/_layout/users/index'
import { Route as DashboardLayoutRevenueIndexImport } from './routes/dashboard/_layout/revenue/index'
import { Route as DashboardLayoutProductsIndexImport } from './routes/dashboard/_layout/products/index'
import { Route as DashboardLayoutOrderIndexImport } from './routes/dashboard/_layout/order/index'
import { Route as DashboardLayoutMessengerIndexImport } from './routes/dashboard/_layout/messenger/index'
import { Route as DashboardLayoutCouponIndexImport } from './routes/dashboard/_layout/coupon/index'
import { Route as DashboardLayoutCategoryIndexImport } from './routes/dashboard/_layout/category/index'
import { Route as DashboardLayoutBlogIndexImport } from './routes/dashboard/_layout/blog/index'
import { Route as DashboardLayoutAddressIndexImport } from './routes/dashboard/_layout/address/index'
import { Route as DashboardLayoutProductsCreateImport } from './routes/dashboard/_layout/products/create'
import { Route as DashboardLayoutCouponCreateImport } from './routes/dashboard/_layout/coupon/create'
import { Route as DashboardLayoutCategoryCreateImport } from './routes/dashboard/_layout/category/create'
import { Route as DashboardLayoutBlogCreateImport } from './routes/dashboard/_layout/blog/create'
import { Route as LayoutRefundUserIdOrderIdImport } from './routes/_layout/refund/$userId.$orderId'
import { Route as LayoutOrderuserIdUserImport } from './routes/_layout/orderuser/$id.user'
import { Route as LayoutExchangeUserIdOrderIdImport } from './routes/_layout/exchange/$userId.$orderId'
import { Route as DashboardLayoutProductsSlugViewdetailImport } from './routes/dashboard/_layout/products/$slug.viewdetail'
import { Route as DashboardLayoutProductsIdEditImport } from './routes/dashboard/_layout/products/$id.edit'
import { Route as DashboardLayoutDetailorderIdDetailorderImport } from './routes/dashboard/_layout/detailorder/$id.detailorder'
import { Route as DashboardLayoutCouponIdShowUserImport } from './routes/dashboard/_layout/coupon/$id.showUser'
import { Route as DashboardLayoutCouponIdEditImport } from './routes/dashboard/_layout/coupon/$id.edit'
import { Route as DashboardLayoutCommentIdCommentImport } from './routes/dashboard/_layout/comment/$id.comment'
import { Route as DashboardLayoutCategoryIdEditImport } from './routes/dashboard/_layout/category/$id.edit'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// const TokenExpiresRoute = TokenExpiresImport.update({
//   path: '/token-expires',
//   getParentRoute: () => rootRoute,
// } as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardSetttingRoute = DashboardSetttingImport.update({
  path: '/settting',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardLayoutIndexRoute = DashboardLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const LayoutThanksIndexRoute = LayoutThanksIndexImport.update({
  path: '/thanks/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutShopIndexRoute = LayoutShopIndexImport.update({
  path: '/shop/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchListIndexRoute = LayoutSearchListIndexImport.update({
  path: '/searchList/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProfileIndexRoute = LayoutProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPaymentOnlineIndexRoute = LayoutPaymentOnlineIndexImport.update({
  path: '/payment-online/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrderuserIndexRoute = LayoutOrderuserIndexImport.update({
  path: '/orderuser/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCheckoutNewIndexRoute = LayoutCheckoutNewIndexImport.update({
  path: '/checkoutNew/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCheckoutIndexRoute = LayoutCheckoutIndexImport.update({
  path: '/checkout/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutChangepasswordIndexRoute = LayoutChangepasswordIndexImport.update({
  path: '/change_password/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCartIndexRoute = LayoutCartIndexImport.update({
  path: '/cart/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBlogIndexRoute = LayoutBlogIndexImport.update({
  path: '/blog/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAddressIndexRoute = LayoutAddressIndexImport.update({
  path: '/address/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutIndexRoute = LayoutAboutIndexImport.update({
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDetailblogSlugRoute = LayoutDetailblogSlugImport.update({
  path: '/detailblog/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCategoriesSlugRoute = LayoutCategoriesSlugImport.update({
  path: '/categories/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBlogTextRoute = LayoutBlogTextImport.update({
  path: '/blog/text',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSlugQuickviewProductRoute = LayoutSlugQuickviewProductImport.update(
  {
    path: '/$slug/quickviewProduct',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutSlugDetailproductRoute = LayoutSlugDetailproductImport.update({
  path: '/$slug/detailproduct',
  getParentRoute: () => LayoutRoute,
} as any)

const DashboardLayoutUsersIndexRoute = DashboardLayoutUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutRevenueIndexRoute =
  DashboardLayoutRevenueIndexImport.update({
    path: '/revenue/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutProductsIndexRoute =
  DashboardLayoutProductsIndexImport.update({
    path: '/products/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutOrderIndexRoute = DashboardLayoutOrderIndexImport.update({
  path: '/order/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutMessengerIndexRoute =
  DashboardLayoutMessengerIndexImport.update({
    path: '/messenger/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCouponIndexRoute = DashboardLayoutCouponIndexImport.update(
  {
    path: '/coupon/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any,
)

const DashboardLayoutCategoryIndexRoute =
  DashboardLayoutCategoryIndexImport.update({
    path: '/category/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutBlogIndexRoute = DashboardLayoutBlogIndexImport.update({
  path: '/blog/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutAddressIndexRoute =
  DashboardLayoutAddressIndexImport.update({
    path: '/address/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutProductsCreateRoute =
  DashboardLayoutProductsCreateImport.update({
    path: '/products/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCouponCreateRoute =
  DashboardLayoutCouponCreateImport.update({
    path: '/coupon/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCategoryCreateRoute =
  DashboardLayoutCategoryCreateImport.update({
    path: '/category/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutBlogCreateRoute = DashboardLayoutBlogCreateImport.update({
  path: '/blog/create',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const LayoutRefundUserIdOrderIdRoute = LayoutRefundUserIdOrderIdImport.update({
  path: '/refund/$userId/$orderId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrderuserIdUserRoute = LayoutOrderuserIdUserImport.update({
  path: '/orderuser/$id/user',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExchangeUserIdOrderIdRoute =
  LayoutExchangeUserIdOrderIdImport.update({
    path: '/exchange/$userId/$orderId',
    getParentRoute: () => LayoutRoute,
  } as any)

const DashboardLayoutProductsSlugViewdetailRoute =
  DashboardLayoutProductsSlugViewdetailImport.update({
    path: '/products/$slug/viewdetail',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutProductsIdEditRoute =
  DashboardLayoutProductsIdEditImport.update({
    path: '/products/$id/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutDetailorderIdDetailorderRoute =
  DashboardLayoutDetailorderIdDetailorderImport.update({
    path: '/detailorder/$id/detailorder',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCouponIdShowUserRoute =
  DashboardLayoutCouponIdShowUserImport.update({
    path: '/coupon/$id/showUser',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCouponIdEditRoute =
  DashboardLayoutCouponIdEditImport.update({
    path: '/coupon/$id/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCommentIdCommentRoute =
  DashboardLayoutCommentIdCommentImport.update({
    path: '/comment/$id/comment',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCategoryIdEditRoute =
  DashboardLayoutCategoryIdEditImport.update({
    path: '/category/$id/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/token-expires': {
      id: '/token-expires'
      path: '/token-expires'
      fullPath: '/token-expires'
      preLoaderRoute: typeof TokenExpiresImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settting': {
      id: '/dashboard/settting'
      path: '/settting'
      fullPath: '/dashboard/settting'
      preLoaderRoute: typeof DashboardSetttingImport
      parentRoute: typeof DashboardImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$slug/detailproduct': {
      id: '/_layout/$slug/detailproduct'
      path: '/$slug/detailproduct'
      fullPath: '/$slug/detailproduct'
      preLoaderRoute: typeof LayoutSlugDetailproductImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$slug/quickviewProduct': {
      id: '/_layout/$slug/quickviewProduct'
      path: '/$slug/quickviewProduct'
      fullPath: '/$slug/quickviewProduct'
      preLoaderRoute: typeof LayoutSlugQuickviewProductImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/blog/text': {
      id: '/_layout/blog/text'
      path: '/blog/text'
      fullPath: '/blog/text'
      preLoaderRoute: typeof LayoutBlogTextImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/categories/$slug': {
      id: '/_layout/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof LayoutCategoriesSlugImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/detailblog/$slug': {
      id: '/_layout/detailblog/$slug'
      path: '/detailblog/$slug'
      fullPath: '/detailblog/$slug'
      preLoaderRoute: typeof LayoutDetailblogSlugImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/address/': {
      id: '/_layout/address/'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof LayoutAddressIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/blog/': {
      id: '/_layout/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LayoutBlogIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/cart/': {
      id: '/_layout/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof LayoutCartIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/change_password/': {
      id: '/_layout/change_password/'
      path: '/change_password'
      fullPath: '/change_password'
      preLoaderRoute: typeof LayoutChangepasswordIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/checkout/': {
      id: '/_layout/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof LayoutCheckoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/checkoutNew/': {
      id: '/_layout/checkoutNew/'
      path: '/checkoutNew'
      fullPath: '/checkoutNew'
      preLoaderRoute: typeof LayoutCheckoutNewIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/orderuser/': {
      id: '/_layout/orderuser/'
      path: '/orderuser'
      fullPath: '/orderuser'
      preLoaderRoute: typeof LayoutOrderuserIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/payment-online/': {
      id: '/_layout/payment-online/'
      path: '/payment-online'
      fullPath: '/payment-online'
      preLoaderRoute: typeof LayoutPaymentOnlineIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/searchList/': {
      id: '/_layout/searchList/'
      path: '/searchList'
      fullPath: '/searchList'
      preLoaderRoute: typeof LayoutSearchListIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/shop/': {
      id: '/_layout/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof LayoutShopIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/thanks/': {
      id: '/_layout/thanks/'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof LayoutThanksIndexImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_layout/exchange/$userId/$orderId': {
      id: '/_layout/exchange/$userId/$orderId'
      path: '/exchange/$userId/$orderId'
      fullPath: '/exchange/$userId/$orderId'
      preLoaderRoute: typeof LayoutExchangeUserIdOrderIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/orderuser/$id/user': {
      id: '/_layout/orderuser/$id/user'
      path: '/orderuser/$id/user'
      fullPath: '/orderuser/$id/user'
      preLoaderRoute: typeof LayoutOrderuserIdUserImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/refund/$userId/$orderId': {
      id: '/_layout/refund/$userId/$orderId'
      path: '/refund/$userId/$orderId'
      fullPath: '/refund/$userId/$orderId'
      preLoaderRoute: typeof LayoutRefundUserIdOrderIdImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard/_layout/blog/create': {
      id: '/dashboard/_layout/blog/create'
      path: '/blog/create'
      fullPath: '/dashboard/blog/create'
      preLoaderRoute: typeof DashboardLayoutBlogCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/category/create': {
      id: '/dashboard/_layout/category/create'
      path: '/category/create'
      fullPath: '/dashboard/category/create'
      preLoaderRoute: typeof DashboardLayoutCategoryCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/coupon/create': {
      id: '/dashboard/_layout/coupon/create'
      path: '/coupon/create'
      fullPath: '/dashboard/coupon/create'
      preLoaderRoute: typeof DashboardLayoutCouponCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/create': {
      id: '/dashboard/_layout/products/create'
      path: '/products/create'
      fullPath: '/dashboard/products/create'
      preLoaderRoute: typeof DashboardLayoutProductsCreateImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/address/': {
      id: '/dashboard/_layout/address/'
      path: '/address'
      fullPath: '/dashboard/address'
      preLoaderRoute: typeof DashboardLayoutAddressIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/blog/': {
      id: '/dashboard/_layout/blog/'
      path: '/blog'
      fullPath: '/dashboard/blog'
      preLoaderRoute: typeof DashboardLayoutBlogIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/category/': {
      id: '/dashboard/_layout/category/'
      path: '/category'
      fullPath: '/dashboard/category'
      preLoaderRoute: typeof DashboardLayoutCategoryIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/coupon/': {
      id: '/dashboard/_layout/coupon/'
      path: '/coupon'
      fullPath: '/dashboard/coupon'
      preLoaderRoute: typeof DashboardLayoutCouponIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/messenger/': {
      id: '/dashboard/_layout/messenger/'
      path: '/messenger'
      fullPath: '/dashboard/messenger'
      preLoaderRoute: typeof DashboardLayoutMessengerIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/order/': {
      id: '/dashboard/_layout/order/'
      path: '/order'
      fullPath: '/dashboard/order'
      preLoaderRoute: typeof DashboardLayoutOrderIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/': {
      id: '/dashboard/_layout/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardLayoutProductsIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/revenue/': {
      id: '/dashboard/_layout/revenue/'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof DashboardLayoutRevenueIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/users/': {
      id: '/dashboard/_layout/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardLayoutUsersIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/category/$id/edit': {
      id: '/dashboard/_layout/category/$id/edit'
      path: '/category/$id/edit'
      fullPath: '/dashboard/category/$id/edit'
      preLoaderRoute: typeof DashboardLayoutCategoryIdEditImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/comment/$id/comment': {
      id: '/dashboard/_layout/comment/$id/comment'
      path: '/comment/$id/comment'
      fullPath: '/dashboard/comment/$id/comment'
      preLoaderRoute: typeof DashboardLayoutCommentIdCommentImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/coupon/$id/edit': {
      id: '/dashboard/_layout/coupon/$id/edit'
      path: '/coupon/$id/edit'
      fullPath: '/dashboard/coupon/$id/edit'
      preLoaderRoute: typeof DashboardLayoutCouponIdEditImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/coupon/$id/showUser': {
      id: '/dashboard/_layout/coupon/$id/showUser'
      path: '/coupon/$id/showUser'
      fullPath: '/dashboard/coupon/$id/showUser'
      preLoaderRoute: typeof DashboardLayoutCouponIdShowUserImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/detailorder/$id/detailorder': {
      id: '/dashboard/_layout/detailorder/$id/detailorder'
      path: '/detailorder/$id/detailorder'
      fullPath: '/dashboard/detailorder/$id/detailorder'
      preLoaderRoute: typeof DashboardLayoutDetailorderIdDetailorderImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/$id/edit': {
      id: '/dashboard/_layout/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/dashboard/products/$id/edit'
      preLoaderRoute: typeof DashboardLayoutProductsIdEditImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/products/$slug/viewdetail': {
      id: '/dashboard/_layout/products/$slug/viewdetail'
      path: '/products/$slug/viewdetail'
      fullPath: '/dashboard/products/$slug/viewdetail'
      preLoaderRoute: typeof DashboardLayoutProductsSlugViewdetailImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSlugDetailproductRoute: typeof LayoutSlugDetailproductRoute
  LayoutSlugQuickviewProductRoute: typeof LayoutSlugQuickviewProductRoute
  LayoutBlogTextRoute: typeof LayoutBlogTextRoute
  LayoutCategoriesSlugRoute: typeof LayoutCategoriesSlugRoute
  LayoutDetailblogSlugRoute: typeof LayoutDetailblogSlugRoute
  LayoutAboutIndexRoute: typeof LayoutAboutIndexRoute
  LayoutAddressIndexRoute: typeof LayoutAddressIndexRoute
  LayoutBlogIndexRoute: typeof LayoutBlogIndexRoute
  LayoutCartIndexRoute: typeof LayoutCartIndexRoute
  LayoutChangepasswordIndexRoute: typeof LayoutChangepasswordIndexRoute
  LayoutCheckoutIndexRoute: typeof LayoutCheckoutIndexRoute
  LayoutCheckoutNewIndexRoute: typeof LayoutCheckoutNewIndexRoute
  LayoutOrderuserIndexRoute: typeof LayoutOrderuserIndexRoute
  LayoutPaymentOnlineIndexRoute: typeof LayoutPaymentOnlineIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutSearchListIndexRoute: typeof LayoutSearchListIndexRoute
  LayoutShopIndexRoute: typeof LayoutShopIndexRoute
  LayoutThanksIndexRoute: typeof LayoutThanksIndexRoute
  LayoutExchangeUserIdOrderIdRoute: typeof LayoutExchangeUserIdOrderIdRoute
  LayoutOrderuserIdUserRoute: typeof LayoutOrderuserIdUserRoute
  LayoutRefundUserIdOrderIdRoute: typeof LayoutRefundUserIdOrderIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSlugDetailproductRoute: LayoutSlugDetailproductRoute,
  LayoutSlugQuickviewProductRoute: LayoutSlugQuickviewProductRoute,
  LayoutBlogTextRoute: LayoutBlogTextRoute,
  LayoutCategoriesSlugRoute: LayoutCategoriesSlugRoute,
  LayoutDetailblogSlugRoute: LayoutDetailblogSlugRoute,
  LayoutAboutIndexRoute: LayoutAboutIndexRoute,
  LayoutAddressIndexRoute: LayoutAddressIndexRoute,
  LayoutBlogIndexRoute: LayoutBlogIndexRoute,
  LayoutCartIndexRoute: LayoutCartIndexRoute,
  LayoutChangepasswordIndexRoute: LayoutChangepasswordIndexRoute,
  LayoutCheckoutIndexRoute: LayoutCheckoutIndexRoute,
  LayoutCheckoutNewIndexRoute: LayoutCheckoutNewIndexRoute,
  LayoutOrderuserIndexRoute: LayoutOrderuserIndexRoute,
  LayoutPaymentOnlineIndexRoute: LayoutPaymentOnlineIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutSearchListIndexRoute: LayoutSearchListIndexRoute,
  LayoutShopIndexRoute: LayoutShopIndexRoute,
  LayoutThanksIndexRoute: LayoutThanksIndexRoute,
  LayoutExchangeUserIdOrderIdRoute: LayoutExchangeUserIdOrderIdRoute,
  LayoutOrderuserIdUserRoute: LayoutOrderuserIdUserRoute,
  LayoutRefundUserIdOrderIdRoute: LayoutRefundUserIdOrderIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DashboardLayoutRouteChildren {
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutBlogCreateRoute: typeof DashboardLayoutBlogCreateRoute
  DashboardLayoutCategoryCreateRoute: typeof DashboardLayoutCategoryCreateRoute
  DashboardLayoutCouponCreateRoute: typeof DashboardLayoutCouponCreateRoute
  DashboardLayoutProductsCreateRoute: typeof DashboardLayoutProductsCreateRoute
  DashboardLayoutAddressIndexRoute: typeof DashboardLayoutAddressIndexRoute
  DashboardLayoutBlogIndexRoute: typeof DashboardLayoutBlogIndexRoute
  DashboardLayoutCategoryIndexRoute: typeof DashboardLayoutCategoryIndexRoute
  DashboardLayoutCouponIndexRoute: typeof DashboardLayoutCouponIndexRoute
  DashboardLayoutMessengerIndexRoute: typeof DashboardLayoutMessengerIndexRoute
  DashboardLayoutOrderIndexRoute: typeof DashboardLayoutOrderIndexRoute
  DashboardLayoutProductsIndexRoute: typeof DashboardLayoutProductsIndexRoute
  DashboardLayoutRevenueIndexRoute: typeof DashboardLayoutRevenueIndexRoute
  DashboardLayoutUsersIndexRoute: typeof DashboardLayoutUsersIndexRoute
  DashboardLayoutCategoryIdEditRoute: typeof DashboardLayoutCategoryIdEditRoute
  DashboardLayoutCommentIdCommentRoute: typeof DashboardLayoutCommentIdCommentRoute
  DashboardLayoutCouponIdEditRoute: typeof DashboardLayoutCouponIdEditRoute
  DashboardLayoutCouponIdShowUserRoute: typeof DashboardLayoutCouponIdShowUserRoute
  DashboardLayoutDetailorderIdDetailorderRoute: typeof DashboardLayoutDetailorderIdDetailorderRoute
  DashboardLayoutProductsIdEditRoute: typeof DashboardLayoutProductsIdEditRoute
  DashboardLayoutProductsSlugViewdetailRoute: typeof DashboardLayoutProductsSlugViewdetailRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutBlogCreateRoute: DashboardLayoutBlogCreateRoute,
  DashboardLayoutCategoryCreateRoute: DashboardLayoutCategoryCreateRoute,
  DashboardLayoutCouponCreateRoute: DashboardLayoutCouponCreateRoute,
  DashboardLayoutProductsCreateRoute: DashboardLayoutProductsCreateRoute,
  DashboardLayoutAddressIndexRoute: DashboardLayoutAddressIndexRoute,
  DashboardLayoutBlogIndexRoute: DashboardLayoutBlogIndexRoute,
  DashboardLayoutCategoryIndexRoute: DashboardLayoutCategoryIndexRoute,
  DashboardLayoutCouponIndexRoute: DashboardLayoutCouponIndexRoute,
  DashboardLayoutMessengerIndexRoute: DashboardLayoutMessengerIndexRoute,
  DashboardLayoutOrderIndexRoute: DashboardLayoutOrderIndexRoute,
  DashboardLayoutProductsIndexRoute: DashboardLayoutProductsIndexRoute,
  DashboardLayoutRevenueIndexRoute: DashboardLayoutRevenueIndexRoute,
  DashboardLayoutUsersIndexRoute: DashboardLayoutUsersIndexRoute,
  DashboardLayoutCategoryIdEditRoute: DashboardLayoutCategoryIdEditRoute,
  DashboardLayoutCommentIdCommentRoute: DashboardLayoutCommentIdCommentRoute,
  DashboardLayoutCouponIdEditRoute: DashboardLayoutCouponIdEditRoute,
  DashboardLayoutCouponIdShowUserRoute: DashboardLayoutCouponIdShowUserRoute,
  DashboardLayoutDetailorderIdDetailorderRoute:
    DashboardLayoutDetailorderIdDetailorderRoute,
  DashboardLayoutProductsIdEditRoute: DashboardLayoutProductsIdEditRoute,
  DashboardLayoutProductsSlugViewdetailRoute:
    DashboardLayoutProductsSlugViewdetailRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  DashboardSetttingRoute: typeof DashboardSetttingRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DashboardSetttingRoute: DashboardSetttingRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/token-expires': typeof TokenExpiresRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/settting': typeof DashboardSetttingRoute
  '/': typeof LayoutIndexRoute
  '/$slug/detailproduct': typeof LayoutSlugDetailproductRoute
  '/$slug/quickviewProduct': typeof LayoutSlugQuickviewProductRoute
  '/blog/text': typeof LayoutBlogTextRoute
  '/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/detailblog/$slug': typeof LayoutDetailblogSlugRoute
  '/about': typeof LayoutAboutIndexRoute
  '/address': typeof LayoutAddressIndexRoute
  '/blog': typeof LayoutBlogIndexRoute
  '/cart': typeof LayoutCartIndexRoute
  '/change_password': typeof LayoutChangepasswordIndexRoute
  '/checkout': typeof LayoutCheckoutIndexRoute
  '/checkoutNew': typeof LayoutCheckoutNewIndexRoute
  '/orderuser': typeof LayoutOrderuserIndexRoute
  '/payment-online': typeof LayoutPaymentOnlineIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/searchList': typeof LayoutSearchListIndexRoute
  '/shop': typeof LayoutShopIndexRoute
  '/thanks': typeof LayoutThanksIndexRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/exchange/$userId/$orderId': typeof LayoutExchangeUserIdOrderIdRoute
  '/orderuser/$id/user': typeof LayoutOrderuserIdUserRoute
  '/refund/$userId/$orderId': typeof LayoutRefundUserIdOrderIdRoute
  '/dashboard/blog/create': typeof DashboardLayoutBlogCreateRoute
  '/dashboard/category/create': typeof DashboardLayoutCategoryCreateRoute
  '/dashboard/coupon/create': typeof DashboardLayoutCouponCreateRoute
  '/dashboard/products/create': typeof DashboardLayoutProductsCreateRoute
  '/dashboard/address': typeof DashboardLayoutAddressIndexRoute
  '/dashboard/blog': typeof DashboardLayoutBlogIndexRoute
  '/dashboard/category': typeof DashboardLayoutCategoryIndexRoute
  '/dashboard/coupon': typeof DashboardLayoutCouponIndexRoute
  '/dashboard/messenger': typeof DashboardLayoutMessengerIndexRoute
  '/dashboard/order': typeof DashboardLayoutOrderIndexRoute
  '/dashboard/products': typeof DashboardLayoutProductsIndexRoute
  '/dashboard/revenue': typeof DashboardLayoutRevenueIndexRoute
  '/dashboard/users': typeof DashboardLayoutUsersIndexRoute
  '/dashboard/category/$id/edit': typeof DashboardLayoutCategoryIdEditRoute
  '/dashboard/comment/$id/comment': typeof DashboardLayoutCommentIdCommentRoute
  '/dashboard/coupon/$id/edit': typeof DashboardLayoutCouponIdEditRoute
  '/dashboard/coupon/$id/showUser': typeof DashboardLayoutCouponIdShowUserRoute
  '/dashboard/detailorder/$id/detailorder': typeof DashboardLayoutDetailorderIdDetailorderRoute
  '/dashboard/products/$id/edit': typeof DashboardLayoutProductsIdEditRoute
  '/dashboard/products/$slug/viewdetail': typeof DashboardLayoutProductsSlugViewdetailRoute
}

export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/token-expires': typeof TokenExpiresRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/settting': typeof DashboardSetttingRoute
  '/': typeof LayoutIndexRoute
  '/$slug/detailproduct': typeof LayoutSlugDetailproductRoute
  '/$slug/quickviewProduct': typeof LayoutSlugQuickviewProductRoute
  '/blog/text': typeof LayoutBlogTextRoute
  '/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/detailblog/$slug': typeof LayoutDetailblogSlugRoute
  '/about': typeof LayoutAboutIndexRoute
  '/address': typeof LayoutAddressIndexRoute
  '/blog': typeof LayoutBlogIndexRoute
  '/cart': typeof LayoutCartIndexRoute
  '/change_password': typeof LayoutChangepasswordIndexRoute
  '/checkout': typeof LayoutCheckoutIndexRoute
  '/checkoutNew': typeof LayoutCheckoutNewIndexRoute
  '/orderuser': typeof LayoutOrderuserIndexRoute
  '/payment-online': typeof LayoutPaymentOnlineIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/searchList': typeof LayoutSearchListIndexRoute
  '/shop': typeof LayoutShopIndexRoute
  '/thanks': typeof LayoutThanksIndexRoute
  '/exchange/$userId/$orderId': typeof LayoutExchangeUserIdOrderIdRoute
  '/orderuser/$id/user': typeof LayoutOrderuserIdUserRoute
  '/refund/$userId/$orderId': typeof LayoutRefundUserIdOrderIdRoute
  '/dashboard/blog/create': typeof DashboardLayoutBlogCreateRoute
  '/dashboard/category/create': typeof DashboardLayoutCategoryCreateRoute
  '/dashboard/coupon/create': typeof DashboardLayoutCouponCreateRoute
  '/dashboard/products/create': typeof DashboardLayoutProductsCreateRoute
  '/dashboard/address': typeof DashboardLayoutAddressIndexRoute
  '/dashboard/blog': typeof DashboardLayoutBlogIndexRoute
  '/dashboard/category': typeof DashboardLayoutCategoryIndexRoute
  '/dashboard/coupon': typeof DashboardLayoutCouponIndexRoute
  '/dashboard/messenger': typeof DashboardLayoutMessengerIndexRoute
  '/dashboard/order': typeof DashboardLayoutOrderIndexRoute
  '/dashboard/products': typeof DashboardLayoutProductsIndexRoute
  '/dashboard/revenue': typeof DashboardLayoutRevenueIndexRoute
  '/dashboard/users': typeof DashboardLayoutUsersIndexRoute
  '/dashboard/category/$id/edit': typeof DashboardLayoutCategoryIdEditRoute
  '/dashboard/comment/$id/comment': typeof DashboardLayoutCommentIdCommentRoute
  '/dashboard/coupon/$id/edit': typeof DashboardLayoutCouponIdEditRoute
  '/dashboard/coupon/$id/showUser': typeof DashboardLayoutCouponIdShowUserRoute
  '/dashboard/detailorder/$id/detailorder': typeof DashboardLayoutDetailorderIdDetailorderRoute
  '/dashboard/products/$id/edit': typeof DashboardLayoutProductsIdEditRoute
  '/dashboard/products/$slug/viewdetail': typeof DashboardLayoutProductsSlugViewdetailRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/token-expires': typeof TokenExpiresRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/settting': typeof DashboardSetttingRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$slug/detailproduct': typeof LayoutSlugDetailproductRoute
  '/_layout/$slug/quickviewProduct': typeof LayoutSlugQuickviewProductRoute
  '/_layout/blog/text': typeof LayoutBlogTextRoute
  '/_layout/categories/$slug': typeof LayoutCategoriesSlugRoute
  '/_layout/detailblog/$slug': typeof LayoutDetailblogSlugRoute
  '/_layout/about/': typeof LayoutAboutIndexRoute
  '/_layout/address/': typeof LayoutAddressIndexRoute
  '/_layout/blog/': typeof LayoutBlogIndexRoute
  '/_layout/cart/': typeof LayoutCartIndexRoute
  '/_layout/change_password/': typeof LayoutChangepasswordIndexRoute
  '/_layout/checkout/': typeof LayoutCheckoutIndexRoute
  '/_layout/checkoutNew/': typeof LayoutCheckoutNewIndexRoute
  '/_layout/orderuser/': typeof LayoutOrderuserIndexRoute
  '/_layout/payment-online/': typeof LayoutPaymentOnlineIndexRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
  '/_layout/searchList/': typeof LayoutSearchListIndexRoute
  '/_layout/shop/': typeof LayoutShopIndexRoute
  '/_layout/thanks/': typeof LayoutThanksIndexRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/_layout/exchange/$userId/$orderId': typeof LayoutExchangeUserIdOrderIdRoute
  '/_layout/orderuser/$id/user': typeof LayoutOrderuserIdUserRoute
  '/_layout/refund/$userId/$orderId': typeof LayoutRefundUserIdOrderIdRoute
  '/dashboard/_layout/blog/create': typeof DashboardLayoutBlogCreateRoute
  '/dashboard/_layout/category/create': typeof DashboardLayoutCategoryCreateRoute
  '/dashboard/_layout/coupon/create': typeof DashboardLayoutCouponCreateRoute
  '/dashboard/_layout/products/create': typeof DashboardLayoutProductsCreateRoute
  '/dashboard/_layout/address/': typeof DashboardLayoutAddressIndexRoute
  '/dashboard/_layout/blog/': typeof DashboardLayoutBlogIndexRoute
  '/dashboard/_layout/category/': typeof DashboardLayoutCategoryIndexRoute
  '/dashboard/_layout/coupon/': typeof DashboardLayoutCouponIndexRoute
  '/dashboard/_layout/messenger/': typeof DashboardLayoutMessengerIndexRoute
  '/dashboard/_layout/order/': typeof DashboardLayoutOrderIndexRoute
  '/dashboard/_layout/products/': typeof DashboardLayoutProductsIndexRoute
  '/dashboard/_layout/revenue/': typeof DashboardLayoutRevenueIndexRoute
  '/dashboard/_layout/users/': typeof DashboardLayoutUsersIndexRoute
  '/dashboard/_layout/category/$id/edit': typeof DashboardLayoutCategoryIdEditRoute
  '/dashboard/_layout/comment/$id/comment': typeof DashboardLayoutCommentIdCommentRoute
  '/dashboard/_layout/coupon/$id/edit': typeof DashboardLayoutCouponIdEditRoute
  '/dashboard/_layout/coupon/$id/showUser': typeof DashboardLayoutCouponIdShowUserRoute
  '/dashboard/_layout/detailorder/$id/detailorder': typeof DashboardLayoutDetailorderIdDetailorderRoute
  '/dashboard/_layout/products/$id/edit': typeof DashboardLayoutProductsIdEditRoute
  '/dashboard/_layout/products/$slug/viewdetail': typeof DashboardLayoutProductsSlugViewdetailRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/token-expires'
    | '/dashboard'
    | '/dashboard/settting'
    | '/'
    | '/$slug/detailproduct'
    | '/$slug/quickviewProduct'
    | '/blog/text'
    | '/categories/$slug'
    | '/detailblog/$slug'
    | '/about'
    | '/address'
    | '/blog'
    | '/cart'
    | '/change_password'
    | '/checkout'
    | '/checkoutNew'
    | '/orderuser'
    | '/payment-online'
    | '/profile'
    | '/searchList'
    | '/shop'
    | '/thanks'
    | '/dashboard/'
    | '/exchange/$userId/$orderId'
    | '/orderuser/$id/user'
    | '/refund/$userId/$orderId'
    | '/dashboard/blog/create'
    | '/dashboard/category/create'
    | '/dashboard/coupon/create'
    | '/dashboard/products/create'
    | '/dashboard/address'
    | '/dashboard/blog'
    | '/dashboard/category'
    | '/dashboard/coupon'
    | '/dashboard/messenger'
    | '/dashboard/order'
    | '/dashboard/products'
    | '/dashboard/revenue'
    | '/dashboard/users'
    | '/dashboard/category/$id/edit'
    | '/dashboard/comment/$id/comment'
    | '/dashboard/coupon/$id/edit'
    | '/dashboard/coupon/$id/showUser'
    | '/dashboard/detailorder/$id/detailorder'
    | '/dashboard/products/$id/edit'
    | '/dashboard/products/$slug/viewdetail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/token-expires'
    | '/dashboard'
    | '/dashboard/settting'
    | '/'
    | '/$slug/detailproduct'
    | '/$slug/quickviewProduct'
    | '/blog/text'
    | '/categories/$slug'
    | '/detailblog/$slug'
    | '/about'
    | '/address'
    | '/blog'
    | '/cart'
    | '/change_password'
    | '/checkout'
    | '/checkoutNew'
    | '/orderuser'
    | '/payment-online'
    | '/profile'
    | '/searchList'
    | '/shop'
    | '/thanks'
    | '/exchange/$userId/$orderId'
    | '/orderuser/$id/user'
    | '/refund/$userId/$orderId'
    | '/dashboard/blog/create'
    | '/dashboard/category/create'
    | '/dashboard/coupon/create'
    | '/dashboard/products/create'
    | '/dashboard/address'
    | '/dashboard/blog'
    | '/dashboard/category'
    | '/dashboard/coupon'
    | '/dashboard/messenger'
    | '/dashboard/order'
    | '/dashboard/products'
    | '/dashboard/revenue'
    | '/dashboard/users'
    | '/dashboard/category/$id/edit'
    | '/dashboard/comment/$id/comment'
    | '/dashboard/coupon/$id/edit'
    | '/dashboard/coupon/$id/showUser'
    | '/dashboard/detailorder/$id/detailorder'
    | '/dashboard/products/$id/edit'
    | '/dashboard/products/$slug/viewdetail'
  id:
    | '__root__'
    | '/_layout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/token-expires'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/dashboard/settting'
    | '/_layout/'
    | '/_layout/$slug/detailproduct'
    | '/_layout/$slug/quickviewProduct'
    | '/_layout/blog/text'
    | '/_layout/categories/$slug'
    | '/_layout/detailblog/$slug'
    | '/_layout/about/'
    | '/_layout/address/'
    | '/_layout/blog/'
    | '/_layout/cart/'
    | '/_layout/change_password/'
    | '/_layout/checkout/'
    | '/_layout/checkoutNew/'
    | '/_layout/orderuser/'
    | '/_layout/payment-online/'
    | '/_layout/profile/'
    | '/_layout/searchList/'
    | '/_layout/shop/'
    | '/_layout/thanks/'
    | '/dashboard/_layout/'
    | '/_layout/exchange/$userId/$orderId'
    | '/_layout/orderuser/$id/user'
    | '/_layout/refund/$userId/$orderId'
    | '/dashboard/_layout/blog/create'
    | '/dashboard/_layout/category/create'
    | '/dashboard/_layout/coupon/create'
    | '/dashboard/_layout/products/create'
    | '/dashboard/_layout/address/'
    | '/dashboard/_layout/blog/'
    | '/dashboard/_layout/category/'
    | '/dashboard/_layout/coupon/'
    | '/dashboard/_layout/messenger/'
    | '/dashboard/_layout/order/'
    | '/dashboard/_layout/products/'
    | '/dashboard/_layout/revenue/'
    | '/dashboard/_layout/users/'
    | '/dashboard/_layout/category/$id/edit'
    | '/dashboard/_layout/comment/$id/comment'
    | '/dashboard/_layout/coupon/$id/edit'
    | '/dashboard/_layout/coupon/$id/showUser'
    | '/dashboard/_layout/detailorder/$id/detailorder'
    | '/dashboard/_layout/products/$id/edit'
    | '/dashboard/_layout/products/$slug/viewdetail'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TokenExpiresRoute: typeof TokenExpiresRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TokenExpiresRoute: TokenExpiresRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/forgot-password",
        "/login",
        "/register",
        "/reset-password",
        "/token-expires",
        "/dashboard"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/$slug/detailproduct",
        "/_layout/$slug/quickviewProduct",
        "/_layout/blog/text",
        "/_layout/categories/$slug",
        "/_layout/detailblog/$slug",
        "/_layout/about/",
        "/_layout/address/",
        "/_layout/blog/",
        "/_layout/cart/",
        "/_layout/change_password/",
        "/_layout/checkout/",
        "/_layout/checkoutNew/",
        "/_layout/orderuser/",
        "/_layout/payment-online/",
        "/_layout/profile/",
        "/_layout/searchList/",
        "/_layout/shop/",
        "/_layout/thanks/",
        "/_layout/exchange/$userId/$orderId",
        "/_layout/orderuser/$id/user",
        "/_layout/refund/$userId/$orderId"
      ]
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/token-expires": {
      "filePath": "token-expires.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_layout",
        "/dashboard/settting"
      ]
    },
    "/dashboard/_layout": {
      "filePath": "dashboard/_layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_layout/",
        "/dashboard/_layout/blog/create",
        "/dashboard/_layout/category/create",
        "/dashboard/_layout/coupon/create",
        "/dashboard/_layout/products/create",
        "/dashboard/_layout/address/",
        "/dashboard/_layout/blog/",
        "/dashboard/_layout/category/",
        "/dashboard/_layout/coupon/",
        "/dashboard/_layout/messenger/",
        "/dashboard/_layout/order/",
        "/dashboard/_layout/products/",
        "/dashboard/_layout/revenue/",
        "/dashboard/_layout/users/",
        "/dashboard/_layout/category/$id/edit",
        "/dashboard/_layout/comment/$id/comment",
        "/dashboard/_layout/coupon/$id/edit",
        "/dashboard/_layout/coupon/$id/showUser",
        "/dashboard/_layout/detailorder/$id/detailorder",
        "/dashboard/_layout/products/$id/edit",
        "/dashboard/_layout/products/$slug/viewdetail"
      ]
    },
    "/dashboard/settting": {
      "filePath": "dashboard/settting.tsx",
      "parent": "/dashboard"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/$slug/detailproduct": {
      "filePath": "_layout/$slug.detailproduct.tsx",
      "parent": "/_layout"
    },
    "/_layout/$slug/quickviewProduct": {
      "filePath": "_layout/$slug.quickviewProduct.tsx",
      "parent": "/_layout"
    },
    "/_layout/blog/text": {
      "filePath": "_layout/blog/text.tsx",
      "parent": "/_layout"
    },
    "/_layout/categories/$slug": {
      "filePath": "_layout/categories/$slug.tsx",
      "parent": "/_layout"
    },
    "/_layout/detailblog/$slug": {
      "filePath": "_layout/detailblog/$slug.tsx",
      "parent": "/_layout"
    },
    "/_layout/about/": {
      "filePath": "_layout/about/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/address/": {
      "filePath": "_layout/address/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/blog/": {
      "filePath": "_layout/blog/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/cart/": {
      "filePath": "_layout/cart/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/change_password/": {
      "filePath": "_layout/change_password/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/checkout/": {
      "filePath": "_layout/checkout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/checkoutNew/": {
      "filePath": "_layout/checkoutNew/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/orderuser/": {
      "filePath": "_layout/orderuser/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/payment-online/": {
      "filePath": "_layout/payment-online/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/profile/": {
      "filePath": "_layout/profile/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/searchList/": {
      "filePath": "_layout/searchList/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/shop/": {
      "filePath": "_layout/shop/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/thanks/": {
      "filePath": "_layout/thanks/index.tsx",
      "parent": "/_layout"
    },
    "/dashboard/_layout/": {
      "filePath": "dashboard/_layout/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/_layout/exchange/$userId/$orderId": {
      "filePath": "_layout/exchange/$userId.$orderId.tsx",
      "parent": "/_layout"
    },
    "/_layout/orderuser/$id/user": {
      "filePath": "_layout/orderuser/$id.user.tsx",
      "parent": "/_layout"
    },
    "/_layout/refund/$userId/$orderId": {
      "filePath": "_layout/refund/$userId.$orderId.tsx",
      "parent": "/_layout"
    },
    "/dashboard/_layout/blog/create": {
      "filePath": "dashboard/_layout/blog/create.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/category/create": {
      "filePath": "dashboard/_layout/category/create.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/coupon/create": {
      "filePath": "dashboard/_layout/coupon/create.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/create": {
      "filePath": "dashboard/_layout/products/create.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/address/": {
      "filePath": "dashboard/_layout/address/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/blog/": {
      "filePath": "dashboard/_layout/blog/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/category/": {
      "filePath": "dashboard/_layout/category/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/coupon/": {
      "filePath": "dashboard/_layout/coupon/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/messenger/": {
      "filePath": "dashboard/_layout/messenger/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/order/": {
      "filePath": "dashboard/_layout/order/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/": {
      "filePath": "dashboard/_layout/products/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/revenue/": {
      "filePath": "dashboard/_layout/revenue/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/users/": {
      "filePath": "dashboard/_layout/users/index.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/category/$id/edit": {
      "filePath": "dashboard/_layout/category/$id.edit.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/comment/$id/comment": {
      "filePath": "dashboard/_layout/comment/$id.comment.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/coupon/$id/edit": {
      "filePath": "dashboard/_layout/coupon/$id.edit.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/coupon/$id/showUser": {
      "filePath": "dashboard/_layout/coupon/$id.showUser.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/detailorder/$id/detailorder": {
      "filePath": "dashboard/_layout/detailorder/$id.detailorder.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/$id/edit": {
      "filePath": "dashboard/_layout/products/$id.edit.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/products/$slug/viewdetail": {
      "filePath": "dashboard/_layout/products/$slug.viewdetail.tsx",
      "parent": "/dashboard/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
